### ISSUE TITLE
Viewer Upgrade Epic

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#393]
Time for spring cleaning (aware it's actually autumn). Ordering issues from #317 and parts of #326 relevant to the viewer package: 

**Core optimisations and upgrades:** 
- [x] Upgrade to latest three version
- [x] Move from loading individual in the scene to Buffer Geometry groups. Afterwards, this entails a rework of
  - [x] Selection logic
  - [x] Clipping (section) box logic
  - [ ] Note: Ensure "visual loading bar" of individual objects appearing in scene still works

**New & enhanced API for:**
- [x] Loading and unloading objects 
- [ ] Loading and unloading object sub-children (optional, can be just filtered out?) 
- [x] Visibility/highlight: controlling an individual object's display externally (ie, hide objects under id x, highlight objects under id x)
- [x] Colouring: allow colouring objects by a given property name (entails exposing, somehow, these property names, or assuming the frontend has access to them). 
- [x] Allow for switching to an orthographic camera (ensure zoom to, zoom extents, canonical views etc. still work in ortho mode)
