### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#511]
Every user of a speckle server is registered with an email. Add email verification step for user who authenticate with a email + password step. The OAuth provider accounts should be automatically treated as accounts with verified email.

## User flow for local auth

* register to a server
* In the long run login is blocked until the email is not verified with a post login page. This should be 2 step rollout:
  * Add a banner? that doesn't block, but warns existing users to initiate the email verification.
  * Verification emails should have an expiry, so sending out a batch to existing users, prob not very useful.
  * After set date? block logging in with an unverified email, force email verification step.
* Receive email with a verify redirect.
* After clicking the verify link, login should proceed to the landing page.

## OAuth user flow

* register with external auth provider
* no email verification should be asked for

## Tasks

- [ ] add test for external provider auto verifiying email
- [ ] server endpoint to send verification email. How long is it valid for?
- [ ] server endpoint to verify email
- [ ] frontend page for post register verification
- [ ] frontend add unverified email banner

## Tasks for later

- [ ] block login of unverified email
- [ ] test unverified email cannot login

**Comment by didimitrie** [comment]
dupe of #113!

**Comment by gjedlicska** [comment]
my bad. Could you @didimitrie take a look at the new description. Added a semi detailed description with tasks.

**Comment by didimitrie** [comment]
"Tasks for later" - agreed, i don't think we should (yet) block unverified email accounts from logging in or using speckle in any way. 

Totally agree re other points: this would be a first stage rollout only, where we display an annoying banner to users in the frontend re email verification. 

Re implementation: 

> add test for external provider auto verifiying email

I feel the email itself, if received, is a test enough. We shouldn't need to pre-validate any emails (beyond what we currently do). This can be skipped. 

Re the rest, some things that come to mind: 
- i'd send the verification email straight away post-registration for new users. old users can click the "send verification email" button that the banner/profile page will display. 
- i'd say a 24h validity is enough. if we change our minds later, we could store the expiry date on the validation token itself. 
- frontend page for post register verification -> that can be resolved via the banner (i can do the frontend parts)

We will need to allow users to change their email address as part of this. Any change to their email should invalidate previous validation and trigger the banner again. 

For the banner, we will also need to know "awaitingValidation: true/false" based wether they have a pending valid email.

**Comment by didimitrie** [comment]
Hey @gjedlicska, I think we can close this? The only outstanding item would be allowing users to change their email - this should be broken out in a new issue.
