### ISSUE TITLE
Various Frontend Bugs and Improvements

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#553]
Not exhaustive: 
- [ ] #560
- [x] **bug** email verification banner cannot be clicked in viewer (closed in #557)
- [x] **bug** expanding sidebar cannot be expanded anymore (latest only? weird regression) (closed in #557)
- [x] improve sidebar in commit/object viewer (possibly separate into individual tabs for filters, data, views, etc)
- [x] **bug** layout issues on stream home page in super wide screen mode
- [x] **bug** console errors due to email verification banner (closed in #557)
- [x] **bug**: refresh branch list in sidebar https://github.com/specklesystems/speckle-server/issues/546
